### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by qwertguy** [sweIhm-ws2018-19/skillproject-fr-32#1]
Erstelle Java files gemäß Aufgabe 4 aus Übungsblatt 1.

**Comment by qwertguy** [comment]
@16uhrpasing @tancetinkaya  Bitte um Review und gegebenfalls nötige Überarbeitung. Danke

**Comment by 16uhrpasing** [comment]
Code wurde reviewt. Konstruktoren wurden hinzugefügt um "1..*" Bedingungen zu erfüllen.

**Comment by tancetinkaya** [comment]
code wurde reviewed durch leichte optimierungen.
