### ISSUE TITLE
Bewertung des Github Wikis

### ISSUE THREAD

**Issue by qwertguy** [sweIhm-ws2018-19/skillproject-fr-32#17]

**Comment by barbarasch** [comment]
Wiki sieht super aus! Bitte nur noch folgendes ergänzen:

**Business Logik:** Ein spaßiger Zeitvertreib beim Autofahren. Aufgrund der verschiedenen Schwierigkeitsgrade erreicht die Anwendung viele Ziel- und Altersgruppen. Durch die Verwendung von Voice wird zudem das Handyverbot beim Autofahren umgangen.
