### ISSUE TITLE
Aufgabe 5

### ISSUE THREAD

**Issue by qwertguy** [sweIhm-ws2018-19/skillproject-fr-32#2]
UML object diagram

**Comment by qwertguy** [comment]
@16uhrpasing @tancetinkaya  Bitte um Review und gegebenfalls nötige Überarbeitung. Danke

**Comment by tancetinkaya** [comment]
code reviewed, alles in Ordnung

**Comment by 16uhrpasing** [comment]
Keine Fehler im Diagramm gefunden. Closed
