### ISSUE TITLE
Answer quiz questions

### ISSUE THREAD

**Issue by qwertguy** [sweIhm-ws2018-19/skillproject-fr-32#27]
As the user, I want to be able to answer the quiz questions alexa gave me.

Acceptance Criteria:

- Alexa processes the questions and tells the user if it was right or wrong.

**Comment by TourismusJessi** [comment]
Richtig! Bei falscher User-Antwort nennt Alexa außerdem die richtige Lösung - bitte noch ergänzen.

**Comment by qwertguy** [comment]
Gut gemacht! Fertig!

**Comment by 16uhrpasing** [comment]
Abgeschlossen.

**Comment by tancetinkaya** [comment]
funktioniert gut! fertig.
