### ISSUE TITLE
Get High-Score

### ISSUE THREAD

**Issue by qwertguy** [sweIhm-ws2018-19/skillproject-fr-32#31]
As the user, I want to be able to hear the High-Score status right after the quiz.

Acceptance Criteria:

- Alexa tells me the High-Score.

**Comment by TourismusJessi** [comment]
Passt, danke!

**Comment by qwertguy** [comment]
Passt. Abgesegnet!

**Comment by 16uhrpasing** [comment]
Gut überarbeitet.
